### ISSUE TITLE
Build failures with cycle: LDSwiftEventSource

### ISSUE THREAD

**Issue by nealmanaktola** [launchdarkly/swift-eventsource#24]
**Is this a support request?**
This issue tracker is maintained by LaunchDarkly SDK developers and is intended for feedback on the SDK code. If you're not sure whether the problem you are having is specifically related to the SDK, or to the LaunchDarkly service overall, it may be more appropriate to contact the LaunchDarkly support team; they can help to investigate the problem and will consult the SDK team if necessary. You can submit a support request by going [here](https://support.launchdarkly.com/hc/en-us/requests/new) or by emailing support@launchdarkly.com.

Note that issues filed on this issue tracker are publicly accessible. Do not provide any private account information on your issues. If your problem is specific to your account, you should submit a support request as described above.

**Describe the bug**
After some builds, we get an error building our app.

❌  error: Cycle inside LDSwiftEventSource; building could produce unreliable results.

Removing the pods directory, and rebuilding tends to fix the issue. However, this happens frequently on CI. Removing the pods directory, and reinstalling pods is a lengthy process which would slow down our CI.

Any ideas 
**To reproduce**
Include this library, and build app. After a few dozen attempts, the build will start failing

**Expected behavior**
Build shouldn't fail

**Logs**
If applicable, add any log output related to your problem.

**SDK version**
The version of this SDK that you are using.

  - LaunchDarkly (5.4.0):
    - LaunchDarkly/Core (= 5.4.0)
  - LaunchDarkly/Core (5.4.0):
    - LDSwiftEventSource (= 1.2.1)
  - LaunchdarklyReactNativeClient (4.0.0):
    - LaunchDarkly (= 5.4.0)
    - React
**Language version, developer tools**
XCode 12.4

**OS/platform**

**Additional context**

**Comment by gwhelanLD** [comment]
Hi @nealmanaktola,

Thanks for bringing this to our attention. Could you clarify for me whether you are reproducing this issue with an application with a direct dependency on `LDSwiftEventSource`, or by including the LaunchDarkly iOS or React Native SDK in an application? This will help us reproduce the issue to track down where we may need to make a change. I've also filed this in our internal issue tracker to be investigated.

Thanks,
@gwhelanLD

**Comment by nealmanaktola** [comment]
> or by including the LaunchDarkly iOS or React Native SDK in an application? 

The latter, via the react native sdk.

Thanks

**Comment by gwhelanLD** [comment]
Thanks for the clarification, we'll start by trying to reproduce by rebuilding our "hello-react-native" application repeatedly then. When we have some results we'll update this issue.

Thanks,
@gwhelanLD

**Comment by gwhelanLD** [comment]
Hi @nealmanaktola,

Sorry for the delay is following up here. I've so far been unable to replicate this issue on my machine. Could you provide your `Podfile` and sample commands or instructions for how you are building the application? I've tried various configurations of our sample application with the version of the React Native SDK specified in this issue. Alternatively, if you can replicate this issue by modifying https://github.com/launchdarkly/hello-react-native, that would also be extremely helpful.

Thanks,
@gwhelanLD

**Comment by gwhelanLD** [comment]
I'm going to close this issue as we haven't received any more detail on the report. We also have regularly running builds in CI that use this dependency through React Native and have not seen this issue (though we do not cache or vendor the pods).

Feel free to reopen if there are more details about this issue we could use to try to replicate.

Thanks,
@gwhelanLD
