### ISSUE TITLE
Should not reconnect, when 204 received

### ISSUE THREAD

**Issue by mkubista** [launchdarkly/swift-eventsource#50]
**Describe the bug**
According to SSE specification ([here](https://html.spec.whatwg.org/multipage/server-sent-events.html)) client should not try to reconnect, when response with 204 http code is received. In this implementation all 2xx codes are treated as success. So when 204 is received and then connection is closed, the library tries to reconnect.

**To reproduce**
Send initial response with 204 code.

**Expected behavior**
Library should not try to reconnect. It should shutdown instead. Also application should be notified, that this happen.

**XCode and Swift version**
For instance, XCode 11.5, Swift 5.1.

**Platform the issue occurs on**
iPhone

**Comment by keelerm84** [comment]
Thank you for bringing this to our attention. I have filed this internall as `sc-166962`. I will update you when we have a resolution.

**Comment by keelerm84** [comment]
Fixed in 3.1.1
