### ISSUE TITLE
[Feat Request] Read response data on error

### ISSUE THREAD

**Issue by jeongshin** [launchdarkly/swift-eventsource#66]
**Is your feature request related to a problem? Please describe.**

I trying to read response data (json error message from server) when request error occurred while creating connection.
But only responseCode is available for UnsuccessfulResponseError.

**Describe the solution you'd like**

`as-is`

```swift
public class UnsuccessfulResponseError: Error {
    /// The HTTP response code received.
    public let responseCode: Int

    /**
     Constructor for an `UnsuccessfulResponseError`.

     - Parameter responseCode: The HTTP response code of the unsuccessful response.
     */
    public init(responseCode: Int) {
        self.responseCode = responseCode
    }
}
```

`to-be`

```swift

public class UnsuccessfulResponseError: Error {
    /// The HTTP response code received.
    public let responseCode: Int

    public let data: Data?
    public let response: Response?
    public let error: Error?
}
```
Can `UnsuccessfulResponseError` be like this? 

I'm newbie learning swift and I tried to solve this by myself but failed to do so

https://github.com/launchdarkly/swift-eventsource/pull/65

**Describe alternatives you've considered**

**Additional context**

**Comment by tanderson-ld** [comment]
Hello @jeongshin , could you provide an example of the raw HTTP Response that contains the data?  I'm interpreting this as the response body contains error data and that is what you want to pipe through the error object?

**Comment by jeongshin** [comment]
> I'm interpreting this as the response body contains error data and that is what you want to pipe through the error object?

That's correct! 

How would you want me to provide raw HTTP response? 

Here's my minimal server code for mocking streaming using express. 

```ts
import bodyParser from 'body-parser';
import express from 'express';
import { concatMap, delay, from, of } from 'rxjs';
import cors from 'cors';

const app = express();

app.use(bodyParser.json());

app.use(cors({ origin: '*' }));

app.use(bodyParser.urlencoded({ extended: false }));

app.listen(3000, () => {
  console.log('start listening');
});

const messages =
  '이제 더이상 ChatGPT의 딱딱하고 한국어가 서투른 서비스를 이용하려고 애쓰지 않아도 됩니다. ChatGPT를 사용하시는 분들에게 최적화되고 발전하고 있는 한국형 AI 뤼튼을 사용해 보시길 권합니다.  진짜 AI는 미치도록 미쳤다 아무래도 회사 집 회사 집 하시는 분들은 AI? 그냥 요즘 애들 이야기 들어보니까 챗지피틴가 피티인가 하는 뭐시기가 요즘 좋다며?하면서 이야기를 하지만 직접 사용해보고 ai에 대해서 조금 더 들어가면  현재도 AI를 어떻게 활용하느냐에 따라서 앞으로 우리가 발전해야 할 시장이나 세상이 달라질 수도 있을 것 같다는 그런 생각이 드는데요 [출처] 뤼튼테크놀로지를 사용 안하고 있다면 인생을 낭비하고 있는 중이다|작성자 부자가될대학생리치원'.split(
    ' '
  );

const headers = {
  'Content-Type': 'text/event-stream; charset=utf-8',
  'Connection': 'keep-alive',
  'Cache-Control': 'no-cache',
};

app.get('/stream', (req, res) => {
  res.writeHead(201, headers);

  console.log('request body from client', req.body, req.headers);

  from(messages)
    .pipe(concatMap((x) => of(x).pipe(delay(100))))
    .subscribe((message) => {
      res.write(
        `data: ${JSON.stringify({
          chunk: message,
        })}\nevent: data\nid: ${new Date().getTime()}\n\n`
      );

      if (messages.findIndex((x) => x === message) === messages.length - 1) {
        res.write(`data: ${JSON.stringify({ end: '[DONE]' })}\n\n`);
      }
    });

  req.on('close', () => {
    console.log('closed connection from client 💥');
  });
});

app.get('/stream/timeout', () => {
  // DO NOTHING
});

app.get('/stream/error', (req, res) => {
  console.log('request');
  res.status(503).json({ message: 'custom error message' });
});
```

I'm sending error message for user as json. 

<img width="442" alt="Screenshot 2023-09-21 at 10 46 29 AM" src="https://github.com/launchdarkly/swift-eventsource/assets/64301935/80f43424-c81e-4544-a86f-e5363996f599">

<img width="586" alt="Screenshot 2023-09-21 at 10 47 19 AM" src="https://github.com/launchdarkly/swift-eventsource/assets/64301935/ffeed9ab-0665-41d6-bcbc-e147513bab5a">

Thanks for reply! 🙌

**Comment by tanderson-ld** [comment]
Hi again @jeongshin .  We discussed this on team and concluded that we won't pick up this feature request.  The SSE specification does not have provisions for parsing response body content and piping that out through the error mechanisms.

**Comment by jeongshin** [comment]
@tanderson-ld Thanks for the clarification!! 👍
