### ISSUE TITLE
How do I add Authentication to the request?

### ISSUE THREAD

**Issue by osirvics** [launchdarkly/swift-eventsource#83]
Will appreciate it if I can get a sample on how authentication, like an access token or cookies can be added to the request

**Comment by keelerm84** [comment]
When constructing the `EventSource`, you must provide a `Config`. This `Config` allows you to provide additional headers that will be sent on each request. You can see an example below.

```swift
import Foundation
import LDSwiftEventSource

class MyEventHandler: EventHandler {
  // implementation ignored for brevity
}

var eventHandler = MyEventHandler()
var config = EventSource.Config(handler: eventHandler, url: url)
config.headers = ["Authorization": "WHATEVER YOU WANT"]

var eventSource = EventSource(config: config)
eventSource.start()
```

**Comment by osirvics** [comment]
Many thanks 🙏
